// bench/tokens/apps/sveltekit/src/routes/contact/+page.svelte
<!-- @feature form -->
<script>
	import { enhance } from '$app/forms';
	let { form } = $props();
</script>

<svelte:head><title>Contact</title></svelte:head>
<form method="POST" use:enhance>
	<label>Name <input name="name" required minlength="1" pattern="[\s\S]{0,50}" value={form?.name ?? ''} />
		{#if form?.errors?.name}<small class="problem">{form.errors.name}</small>{/if}</label>
	<label>Email <input name="email" type="email" required value={form?.email ?? ''} />
		{#if form?.errors?.email}<small class="problem">{form.errors.email}</small>{/if}</label>
	<button>Send</button>
</form>

// bench/tokens/apps/nuxt/pages/contact.vue
<!-- @feature form -->
<script setup>
useHead({ title: 'Contact' })
const form = reactive({ name: '', email: '' })
const errors = ref({})

async function send() {
  try {
    await $fetch('/api/contact', { method: 'POST', body: form })
    await navigateTo('/')
  } catch (e) {
    errors.value = e.data?.data?.errors ?? {}
  }
}
</script>

<template>
  <form @submit.prevent="send">
    <label>Name <input v-model="form.name" required minlength="1" pattern="[\s\S]{0,50}" />
      <small v-if="errors.name" class="problem">{{ errors.name }}</small></label>
    <label>Email <input v-model="form.email" type="email" required />
      <small v-if="errors.email" class="problem">{{ errors.email }}</small></label>
    <button>Send</button>
  </form>
</template>
