// bench/tokens/apps/nextjs/app/contact/page.jsx
// @feature form
'use client';
import { useActionState } from 'react';
import { send } from './actions';

export default function Contact() {
  const [state, action] = useActionState(send, {});
  return (
    <form action={action}>
      <title>Contact</title>
      <label>Name <input name="name" required minLength={1} pattern="[\s\S]{0,50}" defaultValue={state.name} />
        {state.errors?.name && <small className="problem">{state.errors.name}</small>}</label>
      <label>Email <input name="email" type="email" required defaultValue={state.email} />
        {state.errors?.email && <small className="problem">{state.errors.email}</small>}</label>
      <button>Send</button>
    </form>
  );
}

// bench/tokens/apps/sveltekit/src/routes/contact/+page.svelte
<!-- @feature form -->
<script>
	import { enhance } from '$app/forms';
	let { form } = $props();
</script>

<svelte:head><title>Contact</title></svelte:head>
<form method="POST" use:enhance>
	<label>Name <input name="name" required minlength="1" pattern="[\s\S]{0,50}" value={form?.name ?? ''} />
		{#if form?.errors?.name}<small class="problem">{form.errors.name}</small>{/if}</label>
	<label>Email <input name="email" type="email" required value={form?.email ?? ''} />
		{#if form?.errors?.email}<small class="problem">{form.errors.email}</small>{/if}</label>
	<button>Send</button>
</form>
