// bench/tokens/real/sveltekit/src/routes/dashboard/+page.svelte
<!-- @feature auth -->
<script>
	import { enhance } from '$app/forms';
	import Details from '#lib/Details.svelte';
	let { data } = $props();
</script>

<svelte:head><title>Dashboard</title></svelte:head>
<p>Signed in as {data.email}</p>
<form method="POST" action="?/logout" use:enhance><button>Log out</button></form>
<!-- @feature upload -->
{#if data.avatar}<img src="/avatars/{data.id}" alt="Avatar" />{/if}
<a href="/avatar">Change avatar</a>
<!-- @feature component -->
<Details title="Account">
	<p>Signed up with {data.email}</p>
</Details>

// bench/tokens/real/nextjs/app/dashboard/page.jsx
// @feature auth
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { currentUser } from '@/lib/auth';
import Details from '@/components/details';
import { logout } from '../actions';

export const metadata = { title: 'Dashboard' };

export default async function Dashboard() {
  const user = await currentUser();
  if (!user) redirect('/login');
  return (
    <>
      <p>Signed in as {user.email}</p>
      <form action={logout}>
        <button>Log out</button>
      </form>
      {/* @feature upload */}
      {user.avatar && <img src={`/avatars/${user.id}`} alt="Avatar" />}
      <Link href="/avatar">Change avatar</Link>
      {/* @feature component */}
      <Details title="Account">
        <p>Signed up with {user.email}</p>
      </Details>
    </>
  );
}
