// bench/tokens/real/nextjs/app/posts/page.jsx
// @feature crud
import Link from 'next/link';
import { posts } from '@/lib/db';
import Details from '@/components/details';
import { remove } from './actions';
// @feature live
import Live from './live';
// @feature crud

export const metadata = { title: 'Posts' };

export default async function Posts({ searchParams }) {
  const page = Math.max(1, Number((await searchParams).page) || 1);
  const all = [...posts.values()].reverse();
  return (
    <>
      <Link href="/posts/new">New post</Link>
      {all.slice(page * 10 - 10, page * 10).map((post) => (
        <Details key={post.id} title={post.title}>
          <p>{post.body}</p>
          <Link href={`/posts/${post.id}/edit`}>Edit</Link>
          <form action={remove.bind(null, post.id)}>
            <button>Delete</button>
          </form>
        </Details>
      ))}
      {page > 1 && <Link href={`?page=${page - 1}`}>Newer</Link>}
      {all.length > page * 10 && <Link href={`?page=${page + 1}`}>Older</Link>}
      {/* @feature live */}
      <Live />
    </>
  );
}

// bench/tokens/real/sveltekit/src/routes/posts/+page.svelte
<!-- @feature crud -->
<script>
	import { enhance } from '$app/forms';
	import Details from '#lib/Details.svelte';
	// @feature live
	import { invalidateAll } from '$app/navigation';
	import { onMount } from 'svelte';
	// @feature crud
	let { data } = $props();
	// @feature live
	onMount(() => {
		const events = new EventSource('/posts/events');
		events.onmessage = () => invalidateAll();
		return () => events.close();
	});
</script>

<!-- @feature crud -->
<svelte:head><title>Posts</title></svelte:head>
<a href="/posts/new">New post</a>
{#each data.posts as post (post.id)}
	<Details title={post.title}>
		<p>{post.body}</p>
		<a href="/posts/{post.id}/edit">Edit</a>
		<form method="POST" action="?/delete" use:enhance>
			<button name="id" value={post.id}>Delete</button>
		</form>
	</Details>
{/each}
{#if data.page > 1}<a href="?page={data.page - 1}">Newer</a>{/if}
{#if data.more}<a href="?page={data.page + 1}">Older</a>{/if}
