// bench/tokens/real/nextjs/app/login/page.jsx
// @feature auth
'use client';
import { useActionState } from 'react';
import { login } from '../actions';

export default function Login() {
  const [state, action] = useActionState(login, {});
  return (
    <form action={action}>
      <title>Log in</title>
      <label>Email <input name="email" type="email" required defaultValue={state.email} />
        {state.error && <small className="problem">{state.error}</small>}</label>
      <label>Password <input name="password" type="password" /></label>
      <button>Log in</button>
    </form>
  );
}

// bench/tokens/real/sveltekit/src/routes/login/+page.svelte
<!-- @feature auth -->
<script>
	import { enhance } from '$app/forms';
	let { form } = $props();
</script>

<svelte:head><title>Log in</title></svelte:head>
<form method="POST" use:enhance>
	<label>Email <input name="email" type="email" required value={form?.email ?? ''} />
		{#if form?.error}<small class="problem">{form.error}</small>{/if}</label>
	<label>Password <input name="password" type="password" /></label>
	<button>Log in</button>
</form>
