// bench/tokens/real/nextjs/app/signup/page.jsx
// @feature auth
'use client';
import { useActionState } from 'react';
import { signup } from '../actions';

export default function Signup() {
  const [state, action] = useActionState(signup, {});
  return (
    <form action={action}>
      <title>Sign up</title>
      <label>Email <input name="email" type="email" required defaultValue={state.email} />
        {state.errors?.email && <small className="problem">{state.errors.email}</small>}</label>
      <label>Password <input name="password" type="password" required minLength={8} />
        {state.errors?.password && <small className="problem">{state.errors.password}</small>}</label>
      <button>Sign up</button>
    </form>
  );
}

// bench/tokens/real/sveltekit/src/routes/signup/+page.svelte
<!-- @feature auth -->
<script>
	import { enhance } from '$app/forms';
	let { form } = $props();
</script>

<svelte:head><title>Sign up</title></svelte:head>
<form method="POST" use:enhance>
	<label>Email <input name="email" type="email" required value={form?.email ?? ''} />
		{#if form?.errors.email}<small class="problem">{form.errors.email}</small>{/if}</label>
	<label>Password <input name="password" type="password" required minlength="8" />
		{#if form?.errors.password}<small class="problem">{form.errors.password}</small>{/if}</label>
	<button>Sign up</button>
</form>
