// bench/tokens/apps/nuxt/pages/contact.vue
<!-- @feature form -->
<script setup>
useHead({ title: 'Contact' })
const form = reactive({ name: '', email: '' })
const errors = ref({})

async function send() {
  try {
    await $fetch('/api/contact', { method: 'POST', body: form })
    await navigateTo('/')
  } catch (e) {
    errors.value = e.data?.data?.errors ?? {}
  }
}
</script>

<template>
  <form @submit.prevent="send">
    <label>Name <input v-model="form.name" required minlength="1" pattern="[\s\S]{0,50}" />
      <small v-if="errors.name" class="problem">{{ errors.name }}</small></label>
    <label>Email <input v-model="form.email" type="email" required />
      <small v-if="errors.email" class="problem">{{ errors.email }}</small></label>
    <button>Send</button>
  </form>
</template>

// bench/tokens/apps/react/src/pages/Contact.jsx
// @feature form
import { useState } from 'react'
import { useNavigate } from 'react-router'

export default function Contact() {
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [errors, setErrors] = useState({})
  const navigate = useNavigate()

  async function handleSubmit(e) {
    e.preventDefault()
    const res = await fetch('/api/contact', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name, email }),
    })
    if (res.ok) navigate('/')
    else setErrors((await res.json()).errors)
  }

  return (
    <form onSubmit={handleSubmit}>
      <title>Contact</title>
      <label>Name <input value={name} onChange={(e) => setName(e.target.value)} required minLength={1} pattern="[\s\S]{0,50}" />
        {errors.name && <small className="problem">{errors.name}</small>}</label>
      <label>Email <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required />
        {errors.email && <small className="problem">{errors.email}</small>}</label>
      <button>Send</button>
    </form>
  )
}
